import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { createCrossmint, CrossmintAuth } from "@crossmint/server-sdk";
import { Providers } from "./providers/Providers"
import Navbar from "./app-components/Navbar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Benkiko DAO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <SidebarProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Providers>
            {/* <Navbar /> */}
            <>
              <AppSidebar />
              {children}
            </>
          </Providers>
      <Toaster position="top-center" richColors={true} duration={10000} closeButton />
        </body>
      </SidebarProvider>
    </html>

  );
}
